apiVersion: v1
kind: Service
metadata:
  name: bendrocorp-app-v1-service
  labels:
    app: bendrocorp-app-v1-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: bendrocorp-app-v1-deployment